<?php

/**
 * Custom Post Types
 *
 * NOTE: When defining a rewrite slug for a CPT, make it as short as possible.
 * Then use the redirects in .htaccess to redirect this slug with no CPT postname
 * to the actual listing page URL.
 *
 * @package	[[theme-phpdoc-name]]
 * @since	0.1
 */

add_action( 'init', 'pilau_register_post_types', 0 );
/**
 * Register custom post types
 *
 * @since	0.1
 * @return	void
 */
function pilau_register_post_types() {


	/*
	register_post_type(
		'project', array(
			'label'					=> _x( 'projects', 'post type plural name' ),
			'labels'				=> array(
				'name'					=> _x( 'Projects', 'post type general name' ),
				'singular_name'			=> _x( 'Project', 'post type singular name' ),
				'menu_name'				=> _x( 'Projects', 'admin menu' ),
				'name_admin_bar'		=> _x( 'Project', 'add new on admin bar' ),
				'add_new'				=> _x( 'Add New', 'project' ),
				'add_new_item'			=> __( 'Add New Project' ),
				'new_item'				=> __( 'New Project' ),
				'edit_item'				=> __( 'Edit Project' ),
				'view_item'				=> __( 'View Project' ),
				'all_items'				=> __( 'All Projects' ),
				'search_items'			=> __( 'Search Projects' ),
				'parent_item_colon'		=> __( 'Parent Projects:' ),
				'not_found'				=> __( 'No Projects found.' ),
				'not_found_in_trash'	=> __( 'No Projects found in Trash.' )
			),
			'public'				=> true,
			'publicly_queryable'	=> true,
			'show_ui'				=> true,
			'show_in_nav_menus'		=> true,
			'show_in_menu'			=> true,
			'show_in_admin_bar'		=> true,
			'menu_position'			=> 20, // Below Pages
			'menu_icon'				=> 'dashicons-portfolio', // @link https://developer.wordpress.org/resource/dashicons/
			'query_var'				=> true,
			'rewrite'				=> array( 'slug' => 'project', 'with_front' => false ),
			'capability_type'		=> 'post',
			'has_archive'			=> false,
			'hierarchical'			=> false, // Set to true to allow ordering
			'supports'				=> array( 'title', 'editor', 'custom-fields', 'thumbnail', 'revisions' ),
			'taxonomies'			=> array( 'projecttype' ),
		)
	);
	*/


	// Generated by Pilau Init
	//[[custom-post-types]]


}
